name: samuelfujii's site

title: null

google_analytics: "G-VWVHLZZDJ3"

# https://github.com/jekyll/minima/issues/561#issuecomment-748793956
remote_theme: jekyll/minima
plugins:
 - jekyll-remote-theme

